site_name: 'research'
site_description: An informative description
plugins:
  - techdocs-core
nav:
  - Prerequisite: index.md
  - Agile Training: agile_training.md
  - Education Roadmap: education_roadmap.md
  - Administration guide for Red Hat Developer Hub: administration_guide.md
