site_name: 'research'

nav:
  - Home: index.md

plugins:
  - techdocs-core

repo_url: https://github.com/Fortune-Ndlovu/research
edit_uri: https://github.com/Fortune-Ndlovu/research/edit/main/docs/index.md
